"""
Place-data loader and spatial filter for the Neighborhood Explorer.

Loads `backend/data/places_osm.json` once at first use, builds a shapely
STRtree spatial index over every point, and exposes
`places_in_polygon(polygon, categories)` — the runtime hook used by the
`/explore` endpoint to answer "which selected categories fall inside this
isochrone?"

Two JSON files are loaded and merged at startup: `data/places_osm.json`
(generated by `scripts/build_places_osm.py`) and `data/places_curated.json`
(generated by the per-source `scripts/build_*.py` ingestion scripts —
libraries, farmers markets, CPS schools, CPD/CFD stations — which share
`scripts/_curated_common.merge_and_write` to replace-by-source into the
same file).

Index construction is amortized: the STRtree and supporting arrays are
built lazily on the first call and reused for every subsequent request.
This is safe for FastAPI's threadpool — the build is idempotent and the
tree itself is read-only after construction.
"""

from __future__ import annotations

import json
import logging
import threading
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import shapely
# `Point` re-exported for `test_places.py`; the module itself constructs
# points in bulk via `shapely.points()` (OPT-080).
from shapely.geometry import MultiPolygon, Point, Polygon, mapping  # noqa: F401
from shapely.ops import unary_union
from shapely.prepared import prep
from shapely.strtree import STRtree

from utils import quantize_coord

logger = logging.getLogger(__name__)

PLACES_OSM_PATH = Path(__file__).resolve().parent / "data" / "places_osm.json"
PLACES_CURATED_PATH = Path(__file__).resolve().parent / "data" / "places_curated.json"
RESIDENTIAL_PATH = Path(__file__).resolve().parent / "data" / "residential_polygons.json"

# Douglas–Peucker tolerance applied to the unioned residential heatmap before
# `mapping()`. ~0.0005° ≈ 5 m at Chicago latitude — well below what the UI
# resolves at zoom 12–15. Tunable per-file so each clipper can pick its own.
RESIDENTIAL_SIMPLIFY_TOLERANCE: float = 0.0005

_index_lock = threading.Lock()
_places: list[dict[str, Any]] | None = None
_geoms: list[Point] | None = None
_tree: STRtree | None = None

_residential_lock = threading.Lock()
_residential_polys: list[Polygon] | None = None
_residential_tree: STRtree | None = None


def _load_places_file(path: Path, default_source: str) -> list[dict[str, Any]]:
    """Load a places JSON file, normalizing each entry's `source` field.

    `default_source` is the fallback when an entry has no `_source` tag —
    OSM entries don't carry one (the whole file is OSM), but curated
    entries do (one tag per City data feed). The merge step in
    `_curated_common.merge_and_write` writes `_source`; we surface it as
    `source` to the caller (and the API response) and drop the underscore.
    """
    if not path.exists():
        logger.warning("Places file missing at %s — affected categories will be empty", path)
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        logger.error("Failed to read %s (%s: %s) — skipping this source", path, type(e).__name__, e)
        return []
    raw = data.get("places", [])
    out: list[dict[str, Any]] = []
    for p in raw:
        try:
            lat = float(p["lat"])
            lon = float(p["lon"])
        except (KeyError, TypeError, ValueError):
            continue
        out.append({
            "category":    p.get("category"),
            "subcategory": p.get("subcategory"),
            "name":        p.get("name") or "",
            "lat":         lat,
            "lon":         lon,
            "address":     p.get("address"),
            "source":      p.get("_source") or default_source,
        })
    return out


def _load_all_sources() -> list[dict[str, Any]]:
    """Load OSM + curated places, deduping curated entries that collide with OSM.

    Curated entries (libraries from CPL, farmers markets from the city feed)
    take precedence over an OSM entry at the same point: the curated source
    is authoritative for those categories. Dedupe key is `(category, lat_q,
    lon_q)` at ~1 m precision.
    """
    osm = _load_places_file(PLACES_OSM_PATH, default_source="osm")
    curated = _load_places_file(PLACES_CURATED_PATH, default_source="curated")

    if not curated:
        return osm

    # Drop any OSM entry that a curated entry overlaps on (category, ~1m point).
    # `quantize_coord` is called exactly once per entry on each side — the
    # prior list-comprehension that re-quantized inside the membership check
    # did the conversion twice for each OSM row.
    curated_keys: set[tuple[str | None, int, int]] = {
        (p["category"], *quantize_coord(p["lat"], p["lon"]))
        for p in curated
    }
    deduped_osm: list[dict[str, Any]] = []
    for p in osm:
        lat_q, lon_q = quantize_coord(p["lat"], p["lon"])
        if (p["category"], lat_q, lon_q) in curated_keys:
            continue
        deduped_osm.append(p)
    return deduped_osm + curated


def all_places() -> list[dict[str, Any]]:
    """Return every loaded place (OSM + curated, deduped). Triggers the lazy
    index build if needed. Caller must not mutate the returned list.
    """
    places, _ = _ensure_index()
    return places


def _ensure_index() -> tuple[list[dict[str, Any]], STRtree | None]:
    """Lazily build the in-memory point list + STRtree on first call."""
    global _places, _geoms, _tree
    if _places is not None and _tree is not None:
        return _places, _tree
    with _index_lock:
        if _places is not None and _tree is not None:
            return _places, _tree
        places = _load_all_sources()
        if not places:
            _places = []
            _geoms = []
            _tree = STRtree([])  # empty tree is queryable and returns no hits.
            return _places, _tree
        # Bulk shapely.points() over a numpy coord array sidesteps the
        # per-place Python `Point(...)` constructor (~30× faster on the ~16k
        # Chicago places index) — OPT-080.
        coords = np.fromiter(
            (v for p in places for v in (p["lon"], p["lat"])),
            dtype=np.float64, count=len(places) * 2,
        ).reshape(-1, 2)
        geoms = shapely.points(coords)
        _places = places
        _geoms = geoms
        _tree = STRtree(geoms)
        logger.info("Loaded %d places into STRtree index", len(places))
        return _places, _tree


def _normalize_category_filter(categories: Iterable[str] | None) -> set[str] | None:
    """Return a set of allowed `category` keys, or None for "all categories"."""
    if categories is None:
        return None
    cleaned = {c.strip() for c in categories if isinstance(c, str) and c.strip()}
    return cleaned or None


def places_in_polygon(
    polygon,
    categories: Iterable[str] | None = None,
) -> list[dict[str, Any]]:
    """Return every indexed place whose point falls inside `polygon`.

    `polygon` must be a shapely geometry in lon/lat coordinates (the same
    coordinate frame as the explorer's polygon output).

    `categories` filters by the top-level category key. Subcategory
    filtering is intentionally coarse-grained at this layer — the
    frontend's per-subcategory checkboxes can post-filter the response.
    `None` means "all categories" (used by tests and admin tools; the
    real frontend always sends an explicit category list).
    """
    if polygon is None or polygon.is_empty:
        return []

    places, tree = _ensure_index()
    if not places:
        return []

    allowed = _normalize_category_filter(categories)

    # STRtree.query returns indices of geometries whose bounding boxes
    # overlap the query envelope — fast O(log n) prune. Then we run
    # contains() on the candidates for the actual filter.
    candidate_idx = tree.query(polygon)
    if isinstance(candidate_idx, np.ndarray):
        candidate_idx = candidate_idx.tolist()

    # Prepared geometry builds the polygon's edge index once and reuses it
    # across every contains() call. Without this, shapely rebuilds the index
    # per query, which is O(N) on the polygon's vertex count per point.
    prepared = prep(polygon)

    out: list[dict[str, Any]] = []
    for i in candidate_idx:
        place = places[i]
        if allowed is not None and place["category"] not in allowed:
            continue
        if not prepared.contains(_geoms[i]):
            continue
        out.append(place)
    return out


def reset_index_for_tests() -> None:
    """Clear the cached index so test fixtures can swap the data file."""
    global _places, _geoms, _tree, _residential_polys, _residential_tree
    with _index_lock:
        _places = None
        _geoms = None
        _tree = None
    with _residential_lock:
        _residential_polys = None
        _residential_tree = None


def _ensure_residential_index() -> tuple[list[Polygon], STRtree | None]:
    """Lazily load the residential polygon set + STRtree.

    `landuse=residential` polygons are static (refresh yearly), so the
    parsed shapely Polygons + STRtree are cached for the process lifetime.
    """
    global _residential_polys, _residential_tree
    if _residential_polys is not None and _residential_tree is not None:
        return _residential_polys, _residential_tree
    with _residential_lock:
        if _residential_polys is not None and _residential_tree is not None:
            return _residential_polys, _residential_tree
        polys: list[Polygon] = []
        if RESIDENTIAL_PATH.exists():
            try:
                data = json.loads(RESIDENTIAL_PATH.read_text(encoding="utf-8"))
                for ring in data.get("polygons", []):
                    if len(ring) < 4:
                        continue
                    try:
                        poly = Polygon(ring)
                    except (ValueError, TypeError):
                        continue
                    if not poly.is_valid:
                        # `buffer(0)` is shapely's standard self-intersection fix.
                        poly = poly.buffer(0)
                    if poly.is_empty or not isinstance(poly, (Polygon, MultiPolygon)):
                        continue
                    polys.append(poly)
            except (OSError, ValueError) as e:
                logger.error("Failed to read %s (%s: %s)", RESIDENTIAL_PATH, type(e).__name__, e)
        else:
            logger.warning("Residential polygons missing at %s", RESIDENTIAL_PATH)
        _residential_polys = polys
        _residential_tree = STRtree(polys) if polys else STRtree([])
        if polys:
            logger.info("Loaded %d residential polygons", len(polys))
        return _residential_polys, _residential_tree


def residential_heatmap(polygon) -> dict[str, Any] | None:
    """Return a GeoJSON MultiPolygon of residential land clipped to `polygon`.

    Used by the explorer's heatmap fill: each clipped polygon shows where
    people live within the user's reachable area. Returns None when the
    intersection is empty (e.g., isochrone over a downtown loop with no
    `landuse=residential` polygons), which the caller should pass through
    to the response so the frontend can hide the heatmap layer.
    """
    if polygon is None or polygon.is_empty:
        return None
    polys, tree = _ensure_residential_index()
    if not polys:
        return None

    candidate_idx = tree.query(polygon)
    if isinstance(candidate_idx, np.ndarray):
        candidate_idx = candidate_idx.tolist()
    if not candidate_idx:
        return None

    # Intersect each candidate with the isochrone, dropping empties. Union
    # the survivors so the response has one self-consistent geometry — the
    # frontend can then render it as a single fill layer. STRtree already
    # narrowed to bbox-overlapping candidates; `.intersection()` short-
    # circuits internally on truly disjoint pairs, so the prior
    # `prepared.intersects()` second filter was double work.
    pieces = []
    for i in candidate_idx:
        clipped = polys[i].intersection(polygon)
        if clipped.is_empty:
            continue
        pieces.append(clipped)
    if not pieces:
        return None

    merged = unary_union(pieces)
    if merged.is_empty:
        return None
    if merged.geom_type == "GeometryCollection":
        polys_only = [g for g in merged.geoms if g.geom_type in ("Polygon", "MultiPolygon")]
        if not polys_only:
            return None
        merged = unary_union(polys_only)
        if merged.is_empty:
            return None
    merged = merged.simplify(RESIDENTIAL_SIMPLIFY_TOLERANCE, preserve_topology=True)
    if merged.is_empty:
        return None
    if isinstance(merged, Polygon):
        merged = MultiPolygon([merged])
    return mapping(merged)
